(defun dotspacemacs/init ()
    ; Set font
    (spacemacs/set-font "DejaVu Sans Mono" 11)

    (add-to-list 'exec-path "/home/eric/.cabal/bin")

    ; Disable auto-complete and dependencies so that we can use company for completion
    (setq-default dotspacemacs-excluded-packages
      '(auto-complete ac-ispell tern-auto-complete auto-complete-clang enslime edts))

    ; List of contribution to load."
    (setq dotspacemacs-configuration-layers
       '(company-mode haskell javascript python themes-megapack))

    ; Don't use slow OSX fullscreen
    (setq ns-use-native-fullscreen nil)

    ; Escape with Ctrl-j.  Might cause conflict
    ; (setq-default evil-escape-key-sequence (kbd "C-j"))
)

; Runs after dotspacemacs is loaded.
(defun dotspacemacs/config ()
    ; THEMES
    (load-theme 'solarized-dark' true)

    ; ctrl h,l for fast buffer changing.
    (define-key evil-normal-state-map (kbd "C-h") 'evil-prev-buffer)
    (define-key evil-normal-state-map (kbd "C-l") 'evil-next-buffer)

    ; open up buffer list faster
    (define-key evil-normal-state-map (kbd ",b")    'helm-buffers-list)
    (define-key evil-normal-state-map (kbd ", RET") 'helm-semantic-or-imenu)

    ; remove highlights
    (define-key evil-normal-state-map (kbd ", SPC") 'evil-search-highlight-persist-remove-all)

    ; remove highlights
    (define-key evil-normal-state-map (kbd ",s") 'eric-show-or-create-shell)

    ;;;;;; ignore buffers that start and end with *.
    (defun eric-should-ignore-buffers (buffer)
      (string-match-p "\\*.*\\*" buffer))

    (defun eric-get-buffer-index-by-name (name)
      (-find-index (lambda (b) (equal name (buffer-name b))) (buffer-list)))

    (defun eric-get-buffer-by-name (name)
      (let ((shell-index (eric-get-buffer-index-by-name name)))
        (if shell-index (nth shell-index (buffer-list)) nil)))

    (defun eric-show-or-create-shell ()
      (interactive)
      (let* ((shell-buffer (eric-get-buffer-by-name "*shell*"))
             (shell-window (get-buffer-window shell-buffer))
             (current-window (get-buffer-window)))
        (cond ((not shell-buffer) (shell))
              ((not shell-window) (set-buffer shell-buffer))
              (t (select-window shell-window) shell-buffer))
        ))

    (defadvice next-buffer (after avoid-messages-buffer-in-next-buffer)
      "Advice around `next-buffer' to avoid going into the *Messages* buffer."
      (when (eric-should-ignore-buffers (buffer-name))
        (next-buffer)))

    (defadvice previous-buffer (after avoid-messages-buffer-in-previous-buffer)
      "Advice around `previous-buffer' to avoid going into the *Messages* buffer."
      (when (eric-should-ignore-buffers (buffer-name))
        (previous-buffer)))

    (ad-activate 'next-buffer)
    (ad-activate 'previous-buffer)

    ; SNIPPETS
    (setq yas-snippet-dirs
      '("~/.emacs.d/spacemacs/extensions/yasnippet-snippets"))

    ; COMPANY-MODE
    (setq company-idle-delay nil)   ;; only auto-complete on key binding
    (setq company-tooltip-limit 20) ;; use a bigger popup window
    (setq company-mod )

    ; snippet or completion expansion
    (defun company-yasnippet-or-completion ()
      (interactive)
      (if (yas/expansion-at-point)
          (progn (company-abort)
                 (yas/expand))
        (company-complete-common)))

    (defun yas/expansion-at-point ()
      (first (yas--templates-for-key-at-point)))

    (define-key company-active-map (kbd "TAB") 'company-yasnippet-or-completion)
    (define-key company-active-map (kbd "<tab>") 'company-yasnippet-or-completion)
    (define-key company-active-map "\t" 'company-yasnippet-or-completion)
)

;;;;;;;;;;; Autogenerated variables ;;;;;;;;;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-ispell-requires 4)
 '(ahs-case-fold-search nil)
 '(ahs-default-range (quote ahs-range-whole-buffer))
 '(ahs-idle-interval 0.25)
 '(ahs-idle-timer 0 t)
 '(ahs-inhibit-face-list nil)
 '(custom-safe-themes
   (quote
    ("fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "97a2b10275e3e5c67f46ddaac0ec7969aeb35068c03ec4157cf4887c401e74b1" default)))
 '(paradox-github-token t)
 '(ring-bell-function (quote ignore) t)
 '(truncate-lines t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:background nil))))
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
