return {
	{
		"hedyhli/outline.nvim",
		keys = {
			{ "<leader><cr>", "<cmd>Outline<cr>", desc = "Toggle Outline" },
		},
		config = function()
			require("outline").setup({
				highlight_hovered_item = true,
				show_guides = true,
				auto_preview = false,
				position = "right",
				relative_width = true,
				width = 25,
				auto_close = false,
				show_numbers = false,
				show_relative_numbers = false,
				show_symbol_details = true,
				preview_bg_highlight = "Pmenu",
				autofold_depth = nil,
				auto_unfold_hover = true,
				fold_markers = { "", "" },
				wrap = false,
				keymaps = { -- These keymaps can be a string or a table for multiple keys
					close = { "<Esc>", "q" },
					goto_location = "<Cr>",
					focus_location = "o",
					hover_symbol = "<C-space>",
					toggle_preview = "K",
					rename_symbol = "r",
					code_actions = "a",
					fold = "h",
					unfold = "l",
					fold_all = "W",
					unfold_all = "E",
					fold_reset = "R",
				},
				lsp_blacklist = {},
				symbol_blacklist = {},
				symbols = {
					File = { icon = "󰈙", hl = "@lsp.type.file" },
					Module = { icon = "󰏗", hl = "@lsp.type.namespace" },
					Namespace = { icon = "󰅩", hl = "@lsp.type.namespace" },
					Package = { icon = "󰏖", hl = "@lsp.type.namespace" },
					Class = { icon = "󰠱", hl = "@lsp.type.class" },
					Method = { icon = "󰆧", hl = "@lsp.type.method" },
					Property = { icon = "󰜢", hl = "@lsp.type.property" },
					Field = { icon = "󰇽", hl = "@lsp.type.field" },
					Constructor = { icon = "", hl = "@lsp.type.constructor" },
					Enum = { icon = "󰕘", hl = "@lsp.type.enum" },
					Interface = { icon = "󰜰", hl = "@lsp.type.interface" },
					Function = { icon = "󰊕", hl = "@lsp.type.function" },
					Variable = { icon = "󰀫", hl = "@lsp.type.variable" },
					Constant = { icon = "󰏿", hl = "@lsp.type.constant" },
					String = { icon = "󰉾", hl = "@lsp.type.string" },
					Number = { icon = "󰎠", hl = "@lsp.type.number" },
					Boolean = { icon = "", hl = "@lsp.type.boolean" },
					Array = { icon = "󰅪", hl = "@lsp.type.array" },
					Object = { icon = "󰅩", hl = "@lsp.type.object" },
					Key = { icon = "󰌋", hl = "@lsp.type.keyword" },
					Null = { icon = "󰟢", hl = "@lsp.type.null" },
					EnumMember = { icon = "󰖷", hl = "@lsp.type.enumMember" },
					Struct = { icon = "󰙅", hl = "@lsp.type.struct" },
					Event = { icon = "󱐋", hl = "@lsp.type.event" },
					Operator = { icon = "󰆕", hl = "@lsp.type.operator" },
					TypeParameter = { icon = "󰊄", hl = "@lsp.type.typeParameter" },
					Component = { icon = "󰡀", hl = "@lsp.type.component" },
					Fragment = { icon = "󰏎", hl = "@lsp.type.fragment" },
				},
			})
		end,
	},
}
